# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.6.2
_src_path: https://github.com/jupyterlab/extension-template
advanced: true
author_email: goosey15@gmail.com
author_name: Angus Hollands
has_ai_rules: false
has_binder: false
has_settings: true
kind: frontend
labextension_name: jupyterlite-html-exporter
project_short_description: A JupyterLab extension.
python_name: jupyterlite_html_exporter
repository: https://github.com/2i2c-org/jupyterlite-html-exporter
test: true
yarn_linker: pnpm

